skactiveml/utils/_functions.py
skactiveml/utils/tests/test_functions.py

implement simple_batch and test_simple_batch

---

skactiveml/base.py
skactiveml/pool/_expected_error.py
skactiveml/pool/_qbc.py
skactiveml/pool/_random.py
skactiveml/pool/tests/test_expected_error.py
skactiveml/pool/tests/test_pool.py
skactiveml/pool/tests/test_probal.py
skactiveml/pool/tests/test_random.py

59 gen pool tests

---

skactiveml/pool/_qbc.py
skactiveml/pool/tests/test_qbc.py

fixed issue #80 and correctly passed clf to the ensemble in qbc

80 fix init parameter qbc

---

examples/pool/al_cycle.ipynb
skactiveml/classifier/_wrapper.py
skactiveml/classifier/tests/test_wrapper.py

Sample weight issue 84

---

skactiveml/base.py
skactiveml/pool/tests/test_alce.py
skactiveml/utils/_validation.py
skactiveml/utils/tests/test_validation.py

Cost matrix issue 85

---

skactiveml/classifier/_wrapper.py
skactiveml/classifier/tests/test_wrapper.py

Add warnings to sklearn classifier wrapper. Close issue #100.

---

skactiveml/classifier/_pwc.py
skactiveml/classifier/tests/test_pwc.py

Add callable option to PWC metric.

---

skactiveml/utils/_validation.py

Set randind minimum to one to avoid multiplication with 0 and update doc

---

skactiveml/pool/_uncertainty.py

120 fix uncertainty

---

docs/conf.py

Add logo and update release, version in conf.py.

---

docs/conf.py
skactiveml/classifier/_wrapper.py
skactiveml/classifier/tests/test_cmm.py
skactiveml/classifier/tests/test_multi_annot_classifier.py
skactiveml/classifier/tests/test_pwc.py
skactiveml/classifier/tests/test_wrapper.py

138 codecov classifier

---

skactiveml/pool/_epistemic_uncertainty.py
skactiveml/pool/_qbc.py
skactiveml/pool/tests/test_epistemic_uncertainty.py
skactiveml/pool/tests/test_qbc.py
skactiveml/pool/tests/test_uncertainty.py

- Codecov improvemeds for QBC, Uncertainty and Epistemic.

---

skactiveml/pool/_expected_error.py
skactiveml/pool/tests/test_expected_error.py

112 eer fix

---

skactiveml/pool/_qbc.py

Change QBC description

---

.github/workflows/main.yml

Fix sphinx to 4.2 to avoid incompatibilities with sphinx-gallery and sphinx 4.3

---

docs/developers_guide.rst

Small review of the dev guide and comments on the design

Dev guide review

---

.github/workflows/main.yml
requirements_extra.txt

Move dev dependencies to requirements_extra.txt

---

skactiveml/tests/template_budget_manager.py
skactiveml/tests/template_query_strategy.py
skactiveml/tests/utils.py

Includes #303
**Additional context**
Added changes implemented for the estimator to all test templates.

update test to reduce redundancy

---

skactiveml/pool/_bald.py

Remove obsolete parameters in `_bald.py`.

---

skactiveml/pool/_wrapper.py
skactiveml/pool/tests/test_wrapper.py

Mask not subsampled samples using -np.inf

---

.github/workflows/main.yml

Closes #440 
**Additional context**
> Add any other changes not described in the Issue here.

440 workflow parallelization

---

.github/workflows/main.yml
docs/generate.py

447 development documentation

---

skactiveml/pool/_typi_clust.py
skactiveml/pool/tests/test_typi_clust.py

Fix typiclust when batch_size is higher than non-empty clusters

---

docs/examples/pool/_falcun.json
docs/examples/template_pool.py
docs/examples/template_pool_batch.py
docs/examples/template_pool_regression.py
docs/examples/template_pool_regression_batch.py
docs/examples/template_stream.py
docs/refs.bib
skactiveml/pool/__init__.py
skactiveml/pool/_falcun.py
skactiveml/pool/tests/test_falcun.py

456 Implement `Falcun`

---

.github/workflows/external-pull-request.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml

467 pull request workflow

---

skactiveml/classifier/_wrapper.py
skactiveml/classifier/tests/test_wrapper.py
skactiveml/regressor/_wrapper.py
skactiveml/regressor/tests/test_wrapper.py

Closes #473
In `scikit-activeml/skactiveml/regressor/tests/test_wrapper.py` there is still a TODO comment as I couldn't find a scikit-learn regressor that uses `.sample(...)`. Is there any that can be tested?

473 pretrained sklearn

---

skactiveml/pool/_regression_tree_based_al.py
skactiveml/pool/tests/test_regression_tree_based_al.py

Fix `RT-AL` for `method="representativity"`.

---

skactiveml/classifier/_parzen_window_classifier.py
skactiveml/classifier/tests/test_parzen_window_classifier.py
skactiveml/pool/_regression_tree_based_al.py
skactiveml/pool/tests/test_regression_tree_based_al.py

Release `0.6.1`

---

skactiveml/stream/_stream_probabilistic_al.py

Remove unneeded import from `skactiveml/stream/_stream_probabilistic_al.py`.

Remove unneeded import
